server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  #outh2 client 라이브러리 관련 설정.
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 706010677620-t69g6tn1r96p4g09brasuqnarubcoddo.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 3789541977991915
            client-secret: 0a56069a318efc420b4f7e04d7856cbf
            scope:
              - email
              - public_profile

          naver:
            client-id: K1PUwXXYVWZsR7jdayFI
            client-secret: fpyZk8a4ux
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code # 코드를 통해 액세스 토큰을 받고 개인정보를 얻는 방식
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #구글 페이스북은 이미 설정이 되어있어서 안적어줘도 된다만

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해준다

cos:
  key: cos1234